In [2]:
import pandas as pd

In [3]:
df = pd.read_csv("https://raw.githubusercontent.com/mwaskom/seaborn-data/refs/heads/master/titanic.csv")

In [5]:
df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 15 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   survived     891 non-null    int64
 1   pclass       891 non-null    int64
 2   sex          891 non-null    object
 3   age          714 non-null    float64
 4   sibsp        891 non-null    int64
 5   parch        891 non-null    int64
 6   fare         891 non-null    float64
 7   embarked     889 non-null    object
 8   class        891 non-null    object
 9   who          891 non-null    object
 10  adult_male   891 non-null    bool
 11  deck         203 non-null    object
 12  embark_town  889 non-null    object
 13  alive        891 non-null    object
 14  alone        891 non-null    bool
dtypes: bool(2), float64(2), int64(4), object(7)
memory usage: 92.4+ KB

In [7]:
df['who'].unique()

array(['man', 'woman', 'child'], dtype=object)

In [8]:
df['sex'].unique()

array(['male', 'female'], dtype=object)

In [9]:
df['sex'].nunique()

2

In [10]:
# Drop duplicate columns , having alternate
df.drop(['class','embarked','alive'],axis=1,inplace=True)

In [11]:
df.head()

,survived,pclass,sex,age,sibsp,parch,fare,who,adult_male,deck,embark_town,alone
0,0,3,male,22.0,1,0,7.2500,man,True,NaN,Southampton,False
1,1,1,female,38.0,1,0,71.2833,woman,False,C,Cherbourg,False
2,1,3,female,26.0,0,0,7.9250,woman,False,NaN,Southampton,True
3,1,1,female,35.0,1,0,53.1000,woman,False,C,Southampton,False
4,0,3,male,35.0,0,0,8.0500,man,True,NaN,Southampton,True

In [12]:
# Remove deck column bacuse it contains more than 50% data as NaN
df.drop('deck',axis=1,inplace=True)

In [13]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 11 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   survived     891 non-null    int64
 1   pclass       891 non-null    int64
 2   sex          891 non-null    object
 3   age          714 non-null    float64
 4   sibsp        891 non-null    int64
 5   parch        891 non-null    int64
 6   fare         891 non-null    float64
 7   who          891 non-null    object
 8   adult_male   891 non-null    bool
 9   embark_town  889 non-null    object
 10  alone        891 non-null    bool
dtypes: bool(2), float64(2), int64(4), object(3)
memory usage: 64.5+ KB

In [14]:
df['age'].mean()

np.float64(29.69911764705882)

In [15]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 11 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   survived     891 non-null    int64
 1   pclass       891 non-null    int64
 2   sex          891 non-null    object
 3   age          714 non-null    float64
 4   sibsp        891 non-null    int64
 5   parch        891 non-null    int64
 6   fare         891 non-null    float64
 7   who          891 non-null    object
 8   adult_male   891 non-null    bool
 9   embark_town  889 non-null    object
 10  alone        891 non-null    bool
dtypes: bool(2), float64(2), int64(4), object(3)
memory usage: 64.5+ KB

In [16]:
# Check correlation
df.drop(['sex','who','embark_town'],axis=1).corr() * 100

,survived,pclass,age,sibsp,parch,fare,adult_male,alone
survived,100.000000,-33.848104,-7.722109,-3.532250,8.162941,25.730652,-55.708004,-20.336709
pclass,-33.848104,100.000000,-36.922602,8.308136,1.844267,-54.949962,9.403505,13.520715
age,-7.722109,-36.922602,100.000000,-30.824676,-18.911926,9.606669,28.032753,19.827000
sibsp,-3.532250,8.308136,-30.824676,100.000000,41.483770,15.965104,-25.358568,-58.447117
parch,8.162941,1.844267,-18.911926,41.483770,100.000000,21.622494,-34.994275,-58.339768
fare,25.730652,-54.949962,9.606669,15.965104,21.622494,100.000000,-18.202373,-27.183236
adult_male,-55.708004,9.403505,28.032753,-25.358568,-34.994275,-18.202373,100.000000,40.474387
alone,-20.336709,13.520715,19.827000,-58.447117,-58.339768,-27.183236,40.474387,100.000000

In [17]:
df['pclass'].unique()

array([3, 1, 2])

In [18]:
df.groupby('pclass')['age'].mean()

pclass
1    38.233441
2    29.877630
3    25.140620
Name: age, dtype: float64

In [19]:
# impute age based on Pclass in 177 records (which contain NaN value)
def fill_age(cols):
  age = cols[0]
  pclass = cols[1]
  if pd.isnull(age):  # 177 records
    if pclass==1:
      return 38
    elif pclass==2:
      return 30
    else:
      return 25
  else:   # 714 records
    return age

In [20]:
df['age'] = df[['age','pclass']].apply(fill_age,axis=1)

/tmp/ipykernel_1455/1384706313.py:3: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  age = cols[0]
/tmp/ipykernel_1455/1384706313.py:4: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  pclass = cols[1]

In [21]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 11 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   survived     891 non-null    int64
 1   pclass       891 non-null    int64
 2   sex          891 non-null    object
 3   age          891 non-null    float64
 4   sibsp        891 non-null    int64
 5   parch        891 non-null    int64
 6   fare         891 non-null    float64
 7   who          891 non-null    object
 8   adult_male   891 non-null    bool
 9   embark_town  889 non-null    object
 10  alone        891 non-null    bool
dtypes: bool(2), float64(2), int64(4), object(3)
memory usage: 64.5+ KB

In [22]:
# Check correlation
df.drop(['sex','who','embark_town'],axis=1).corr() * 100

,survived,pclass,age,sibsp,parch,fare,adult_male,alone
survived,100.000000,-33.848104,-5.015605,-3.532250,8.162941,25.730652,-55.708004,-20.336709
pclass,-33.848104,100.000000,-40.426187,8.308136,1.844267,-54.949962,9.403505,13.520715
age,-5.015605,-40.426187,100.000000,-24.354914,-17.526358,12.104389,24.371834,17.033337
sibsp,-3.532250,8.308136,-24.354914,100.000000,41.483770,15.965104,-25.358568,-58.447117
parch,8.162941,1.844267,-17.526358,41.483770,100.000000,21.622494,-34.994275,-58.339768
fare,25.730652,-54.949962,12.104389,15.965104,21.622494,100.000000,-18.202373,-27.183236
adult_male,-55.708004,9.403505,24.371834,-25.358568,-34.994275,-18.202373,100.000000,40.474387
alone,-20.336709,13.520715,17.033337,-58.447117,-58.339768,-27.183236,40.474387,100.000000

In [23]:
# df.dropna().info()
df.dropna(inplace=True)

In [24]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 889 entries, 0 to 890
Data columns (total 11 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   survived     889 non-null    int64
 1   pclass       889 non-null    int64
 2   sex          889 non-null    object
 3   age          889 non-null    float64
 4   sibsp        889 non-null    int64
 5   parch        889 non-null    int64
 6   fare         889 non-null    float64
 7   who          889 non-null    object
 8   adult_male   889 non-null    bool
 9   embark_town  889 non-null    object
 10  alone        889 non-null    bool
dtypes: bool(2), float64(2), int64(4), object(3)
memory usage: 71.2+ KB

In [25]:
df['sex'].unique()

array(['male', 'female'], dtype=object)

In [26]:
df['who'].unique()

array(['man', 'woman', 'child'], dtype=object)

In [27]:
df['embark_town'].unique()

array(['Southampton', 'Cherbourg', 'Queenstown'], dtype=object)

In [28]:
pd.get_dummies(df['sex'])

     female   male
0     False   True
1      True  False
2      True  False
3      True  False
4     False   True
..      ...    ...
886   False   True
887    True  False
888    True  False
889   False   True
890   False   True

[889 rows x 2 columns]

In [29]:
pd.get_dummies(df['sex'], drop_first=True)

      male
0     True
1    False
2    False
3    False
4     True
..     ...
886   True
887  False
888  False
889   True
890   True

[889 rows x 1 columns]

In [30]:
pd.get_dummies(df['who'])

     child    man  woman
0    False   True  False
1    False  False   True
2    False  False   True
3    False  False   True
4    False   True  False
..     ...    ...    ...
886  False   True  False
887  False  False   True
888  False  False   True
889  False   True  False
890  False   True  False

[889 rows x 3 columns]

In [31]:
pd.get_dummies(df['who'],drop_first=True)

       man  woman
0     True  False
1    False   True
2    False   True
3    False   True
4     True  False
..     ...    ...
886   True  False
887  False   True
888  False   True
889   True  False
890   True  False

[889 rows x 2 columns]

In [32]:
pd.get_dummies(df['embark_town'],drop_first=True)

     Queenstown  Southampton
0         False         True
1         False        False
2         False         True
3         False         True
4         False         True
..          ...          ...
886       False         True
887       False         True
888       False         True
889       False        False
890        True        False

[889 rows x 2 columns]

In [33]:
df = pd.concat([df,pd.get_dummies(df['sex'],drop_first=True),pd.get_dummies(df['who'],drop_first=True),pd.get_dummies(df['embark_town'],drop_first=True)],axis=1)

In [34]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 889 entries, 0 to 890
Data columns (total 16 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   survived     889 non-null    int64
 1   pclass       889 non-null    int64
 2   sex          889 non-null    object
 3   age          889 non-null    float64
 4   sibsp        889 non-null    int64
 5   parch        889 non-null    int64
 6   fare         889 non-null    float64
 7   who          889 non-null    object
 8   adult_male   889 non-null    bool
 9   embark_town  889 non-null    object
 10  alone        889 non-null    bool
 11  male         889 non-null    bool
 12  man          889 non-null    bool
 13  woman        889 non-null    bool
 14  Queenstown   889 non-null    bool
 15  Southampton  889 non-null    bool
dtypes: bool(7), float64(2), int64(4), object(3)
memory usage: 75.5+ KB

In [35]:
df.drop(['sex','who','embark_town'],axis=1,inplace=True)

In [36]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 889 entries, 0 to 890
Data columns (total 13 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   survived     889 non-null    int64
 1   pclass       889 non-null    int64
 2   age          889 non-null    float64
 3   sibsp        889 non-null    int64
 4   parch        889 non-null    int64
 5   fare         889 non-null    float64
 6   adult_male   889 non-null    bool
 7   alone        889 non-null    bool
 8   male         889 non-null    bool
 9   man          889 non-null    bool
 10  woman        889 non-null    bool
 11  Queenstown   889 non-null    bool
 12  Southampton  889 non-null    bool
dtypes: bool(7), float64(2), int64(4)
memory usage: 54.7 KB

In [37]:
x = df.drop('survived',axis=1)
y = df['survived']

In [38]:
from sklearn.model_selection import train_test_split
x_train, x_test , y_train,y_test =  train_test_split(x,y,test_size=.2)

In [39]:
x_test.shape

(178, 12)

In [40]:
x_train.shape

(711, 12)

In [41]:
from sklearn.linear_model import LogisticRegression

In [42]:
logr = LogisticRegression()

In [43]:
# train the model
logr.fit(x_train,y_train)

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

LogisticRegression()

In [44]:
# predict taget column values
y_pred = logr.predict(x_test)

In [45]:
# check the accuracy
from sklearn.metrics import accuracy_score,confusion_matrix

In [46]:
accuracy_score(y_test,y_pred)*100

80.33707865168539

In [47]:
y_pred[0:5]

array([1, 0, 0, 0, 1])

In [48]:
y_test[0:5]

166    1
469    1
149    0
384    0
726    1
Name: survived, dtype: int64

In [49]:
confusion_matrix(y_test,y_pred)

array([[100,  14],
       [ 21,  43]])

In [51]:
df.head()

,survived,pclass,age,sibsp,parch,fare,adult_male,alone,male,man,woman,Queenstown,Southampton
0,0,3,22.0,1,0,7.2500,True,False,True,True,False,False,True
1,1,1,38.0,1,0,71.2833,False,False,False,False,True,False,False
2,1,3,26.0,0,0,7.9250,False,True,False,False,True,False,True
3,1,1,35.0,1,0,53.1000,False,False,False,False,True,False,True
4,0,3,35.0,0,0,8.0500,True,True,True,True,False,False,True

In [52]:
new_passenger = pd.DataFrame({
    'pclass': [3],
    'age': [25],
    'sibsp': [0],
    'parch': [0],
    'fare': [7.25],
    'adult_male': [True],
    'alone': [True],
    'male': [True],
    'man': [True],
    'woman': [False],
    'Queenstown': [False],
    'Southampton': [True]
})

In [53]:
prediction = logr.predict(new_passenger)
print(prediction)

[0]

In [54]:
new_passenger2 = pd.DataFrame({
    'pclass': [3],
    'age': [25],
    'sibsp': [0],
    'parch': [0],
    'fare': [7.25],
    'adult_male': [False],
    'alone': [True],
    'male': [False],
    'man': [False],
    'woman': [True],
    'Queenstown': [False],
    'Southampton': [True]
})

In [55]:
prediction = logr.predict(new_passenger2)
print(prediction)

[1]